// Sagas: long, server-wide story arcs that every mission moves forward. Built on canon threads
// (lore/04-live-story-arcs.md, lore/05-dm-hooks.md) and on missions that really exist in the game
// (Alpha 4.x): the Onyx Facilities' Jorrit Dossier, Storm Breaker's Farro data centres and Lazarus labs,
// InterSec's Vanduul-Tech Smugglers and Tactical Strike, QV Breaker Stations, Hunt Frontier Fighters,
// Siege of Orison, Hathor's Align & Mine, Alliance Aid, Wikelo's Emporium and the Pyro contested zones.
//
// Each saga has a public premise, a villain known only by an alias, five acts and ten LEADS (two per act).
// A lead is a real thing you do in game (where, which contract, what you'll find there). Playing it out
// reveals its clue. Each character also carries personal TIDBITS: secrets from their own past that point
// at the BOND, the big reveal that ties the whole crew together at the finale.
//
// Placeholders: {shadow} villain alias, {truename} real identity (secret until the finale),
// {lieutenant} the villain's right hand (an NPC from a player's own story when possible).
// Tidbits also use {short} {home} {npc} {origin} and pronouns ({they} {their}…).
// lead.activity is a key of OBJECTIVES / CONTRACT_GUIDE; lead.match matches real contract titles.

export const SAGAS = [
  {
    id: "hyperion",
    title: "The Hyperion Inheritance",
    thread: "asd",
    systems: ["Stanton", "Pyro", "Nyx"],
    premise: "Regen is failing across the Empire, and ASD says the Jorrit scandal is over. It isn't. Someone calling themselves {shadow} has picked up Project Hyperion where Dr. Logan Jorrit left off: Vanduul tissue from Nyx, irradiated Valakkar pearls from Pyro I, and human test subjects from anywhere nobody will miss them.",
    truth: "{shadow} is {truename}, the ASD executive who co-signed Jorrit's Second Life Initiative. Jorrit was the scapegoat. {truename} kept the Lazarus index, ASD's hidden copy of thousands of regen imprints, and plans to sell regen that never fails to whoever can pay, and let it fail for everyone else.",
    bond: "Here's the truth that ties you together: every one of you has been regenerated at least once, and every one of your imprints was copied into the Lazarus index. {crew}, you weren't patients. You were the control group. {truename} has a backup of each of you, and the means to decide whether you come back.",
    acts: [
      { name: "Cold Files", goal: "Find out who is still paying for Jorrit's work." },
      { name: "The Buyers", goal: "Follow the specimens through Pyro." },
      { name: "Vanduul Parts", goal: "Trace the Vanduul tissue back from Nyx." },
      { name: "Living Proof", goal: "Learn what the Lazarus labs made, and who survived it." },
      { name: "Site-B", goal: "Find {shadow}'s name in Jorrit's last experiment." },
    ],
    leads: [
      { system: "Stanton", where: "an Onyx Facility on one of Stanton's moons", activity: "investigate", contract: "Hockrow Agency's **Jorrit Dossier** missions (**Investigation** tab), personnel and research files", find: "the personnel files in the facility's wings", match: /onyx|jorrit|dossier|personnel|research files/i,
        text: "An Onyx personnel file lists a payment code that's still active, months after the facilities were 'abandoned'. The account is called {shadow}." },
      { system: "Stanton", where: "an Onyx Facility (energy anomaly)", activity: "investigate", contract: "Hockrow's **Jorrit Dossier: Retrieve Energy Anomaly Data** or engineering files (**Investigation**)", find: "the energy anomaly data", match: /anomaly|engineering files|onyx|jorrit/i,
        text: "Someone inside the Hockrow Agency is selling copies of Arken Mallor's case file on Jorrit (JD10285). The buyer pays through {shadow}'s account." },
      { system: "Pyro", where: "the Farro Data Centers on Pyro IV", activity: "fps", contract: "No contract needed: Storm Breaker. Take the turrets, then the ASD keycard in the emergency shelter", find: "the ASD maintenance keycard and the data-centre logs", match: /farro|data cent|asd|storm/i,
        text: "Farro data-centre logs show specimen shipments kept leaving Pyro I after Jorrit was put on leave, signed off by {lieutenant}." },
      { system: "Pyro", where: "Checkmate Station's contested zone (Monox L4)", activity: "fps", contract: "No contract needed: the contested zone. A **Blue Security Keycard** room holds the ledger", find: "loot behind a Blue Security Keycard door", match: /checkmate|contested|keycard/i,
        text: "A gang ledger at Checkmate prices people by 'imprint quality'. Every sale went to the same buyer: {lieutenant}, for {shadow}." },
      { system: "Nyx", where: "a QV Logistics station in Nyx", activity: "fps", contract: "InterSec's **Vanduul-Tech Smugglers** (needs Junior Contractor rank with InterSec)", find: "the decrypted data packets", match: /vanduul|smuggler|qv|intersec/i,
        text: "The smugglers' data packets show the Vanduul plating and tissue sold to ASD's Onyx labs. The end buyer on every packet: {shadow}." },
      { system: "Nyx", where: "the Glaciem Ring or the Keeger Belt (Nyx)", activity: "bounty", contract: "A **Bounty Hunter** contract on a Shattered Blade or smuggler target in Nyx", find: "the bounty target (the kill or capture is the stand-in)", match: /bounty|shattered|blade|recover vanduul/i,
        text: "{lieutenant} pays the Shattered Blade to guard the Vanduul supply line, in credits that came straight out of ASD's research budget." },
      { system: "Pyro", where: "the Lazarus labs in the Pyro I storms (Phoenix and Tithonus)", activity: "fps", contract: "No contract needed: Storm Breaker. Take the automated shuttle in, wear radiation gear, print the **Specimen Cache Access** card", find: "the specimen cache", match: /lazarus|specimen|phoenix|tithonus/i,
        text: "The Second Life Initiative was never only about the Valakkar. A Lazarus log lists a human subject regenerated eleven times who 'came back whole every time'." },
      { system: "Stanton", where: "a Wikelo Emporium (Kinga, Selo or Dasi Station)", activity: "rp", contract: "Trade at Wikelo's Emporium, or take a Wikelo collection contract", find: "Wikelo himself: land at the Emporium and trade or take a contract", match: /wikelo/i,
        text: "Wikelo buys irradiated Valakkar pearls, and remembers every seller. One courier always paid in ASD scrip and always asked for the same thing back: 'nothing that can be traced to {shadow}'." },
      { system: "Stanton", where: "Site-B in an Onyx Facility", activity: "investigate", contract: "Hockrow's Phase 3 Jorrit Dossier: the Reagent code (Engineering), the Catalyst code (Research), then run the experiment in Site-B", find: "the Site-B experiment results", match: /site.?b|reagent|catalyst|lab sample|hyperion/i,
        text: "Jorrit's Site-B notes name the co-signer on Project Hyperion. It isn't Jorrit's handwriting on the order. It's {shadow}'s." },
      { system: "Pyro", where: "the Lazarus altar in the Pyro I storms", activity: "combat", contract: "No contract needed: summon and kill the Apex Valakkar", find: "the Apex Valakkar's pearl", match: /valakkar|apex|pearl/i,
        text: "The apex's pearl carries an ASD tracker. It's been pinging the same private ship in the Pyro I storms every 72 hours." },
    ],
    tidbits: [
      { text: "{short}'s regen record has a three-day gap that no clinic can explain.", find: "a regen-pod log in a Lazarus lab (Pyro I)" },
      { text: "{npc} signed a consent form at an ASD clinic, in {short}'s name. {short} never signed anything.", find: "the personnel files in an Onyx Facility" },
      { text: "The first time {short} died, {they} woke up somewhere {they} had never been. The medical bill was paid by an account called {shadow}.", find: "any hospital: respawn or visit one (Orison, Lorville, Area18, New Babbage, Levski)" },
      { text: "A Farro data-centre backup has a folder labelled with {short}'s full name and {their} blood type.", find: "a Farro data centre on Pyro IV" },
      { text: "Someone from {home} sold {short}'s medical history years ago, for less than a ship's fuel.", find: "a datapad at a Checkmate or Orbituary contested zone" },
      { text: "{short} isn't the original. {Their} first imprint was 'refined' once already, and {they} remember a laugh that isn't {their} own.", find: "the Site-B experiment results (Onyx)" },
    ],
    bondHint: { text: "{short}'s imprint has an index number. So does every crewmate's. They're all in the same block.", find: "the Lazarus specimen cache (Pyro I)" },
    finale: "Go into the Pyro I storms, take the Lazarus index, and face {truename}. What you do with a backup of every one of you decides the ending.",
    finalePlay: { system: "Pyro", where: "the Lazarus labs in the Pyro I storms", contract: "No contract needed: a full Storm Breaker run as a crew. Everyone hostile inside works for {truename}, the specimen cache is the Lazarus index, and the Apex Valakkar is the guardian you have to get past", activity: "fps" },
    sideJobs: {
      Mercenary: "Every gang outpost you clear is one less place {shadow} can hide a test subject.",
      "Bounty Hunter": "Bounty targets talk. One of them might have sold a body to {lieutenant}.",
      Hauling: "Medical cargo is how {shadow} moves specimens. Watch the manifests.",
      Delivery: "Couriers carry ASD's dirty data. Read the label before you hand it over.",
      Investigation: "Anything ASD left behind is a thread back to {shadow}.",
      Search: "Missing people in this story aren't always missing. Some were sold.",
      salvage: "Wrecks carry black boxes, and ASD's couriers crash too.",
      other: "Every job puts you somewhere {shadow}'s people have been. Keep your eyes open.",
    },
  },
  {
    id: "embers",
    title: "Embers of the Frontier",
    thread: "frontier",
    systems: ["Pyro", "Stanton"],
    premise: "The Headhunters executed Amelia Boyd, and the Frontier Fighters were supposed to die with her. But someone is pulling the scattered cells back together under a new name, {shadow}, and attacks are starting again on both sides of the jump, just like the Slicers.",
    truth: "{shadow} is {truename}, who was never a Frontier Fighter. They were the UEE liaison who quietly armed Boyd and staged the Slicer attacks, and they want a war in Pyro that would make them indispensable to the Empire.",
    bond: "Here's what ties you together: you're the frame. {crew}, every one of you is on {shadow}'s list, the people chosen to take the blame for the massacre at Ruin Station. Your ships, your names, your faces. Every job that brought you here was arranged so you'd be standing in the right place when it happened.",
    acts: [
      { name: "Sparks", goal: "Work out who is behind the new attacks." },
      { name: "The Old Cells", goal: "Find the Frontier Fighter cells that survived Boyd." },
      { name: "A Name in Uniform", goal: "Learn who is supplying them from Stanton." },
      { name: "False Flags", goal: "Stop the attack meant to drag the UEE into Pyro." },
      { name: "The Handler", goal: "Unmask {shadow} before the war starts." },
    ],
    leads: [
      { system: "Pyro", where: "a Frontier Fighter hideout in Pyro", activity: "bounty", contract: "**Hunt Frontier Fighters** contracts from the Citizens for Prosperity or the Headhunters", find: "the weapons on the bodies", match: /frontier|hunt|fighter/i,
        text: "The weapons used in the latest attack carry Navy serial numbers that were officially destroyed." },
      { system: "Pyro", where: "a Citizens for Prosperity site in Pyro", activity: "fps", contract: "The **Mercenary** contract **Clear Citizens for Prosperity Servers**, or a CFP defend contract", find: "the CFP server data", match: /servers|citizens for prosperity|cfp|defend/i,
        text: "The CFP's own servers hold a list of Frontier Fighter sympathisers. Someone has been deleting names from it, using a UEE login." },
      { system: "Stanton", where: "the Stanton–Pyro jump (a hauling run through it)", activity: "haul", contract: "A **Hauling** contract between Stanton and Pyro (Red Wind Linehaul or Covalex)", find: "the cargo manifest", match: /haul|cargo|freight|supply|red wind|covalex/i,
        text: "Frontier Fighter caches are being restocked by a hauler with Stanton clearance codes. The codes were issued to {lieutenant}." },
      { system: "Pyro", where: "the Derelict Outpost on Fuego (an old Headhunter stash point)", activity: "investigate", contract: "No contract needed: go and search it", find: "a stash datapad", match: /fuego|derelict|stash/i,
        text: "{lieutenant} is the go-between who meets the cells. They're paid in UEE scrip, never in gang credits." },
      { system: "Pyro", where: "a Citizens for Prosperity outpost (Shepherd's Rest, Bloom, or Yang's Place, Monox)", activity: "fps", contract: "A **Mercenary** defend contract at a CFP site", find: "the attackers' orders", match: /defend|occupants|protect/i,
        text: "The attackers' orders plan a hit on a CFP outpost, dressed up to look like the Headhunters did it." },
      { system: "Stanton", where: "Orison (the Siege of Orison)", activity: "fps", contract: "The instanced **Siege of Orison**: take the platforms, disable the IFF inverters, kill Mendo Ren", find: "an IFF inverter's supply tag", match: /orison|siege|nine tails|inverter/i,
        text: "The IFF inverters the Nine Tails used at Orison came from the same supplier as the Frontier Fighters' new guns. They were bought with a retired Navy liaison cipher." },
      { system: "Pyro", where: "Ruin Station's Ghost Arena (contested zone)", activity: "fps", contract: "No contract needed: the Ghost Arena. Crypt, Wasteland and Last Resort keycards", find: "Boyd's last recording in a locked room", match: /ruin|ghost arena|crypt|wasteland|last resort/i,
        text: "Boyd's last recording mentions a 'friend in the Empire' who promised her ships that never came." },
      { system: "Pyro", where: "PYAM-EXHANG-0-1 (the Executive Hangar)", activity: "fps", contract: "Collect the seven compboards from Checkmate, Orbituary and Ruin, then open the Executive Hangar", find: "the hangar's registry", match: /exhang|executive|compboard/i,
        text: "The Executive Hangar's registry lists a ship gifted to a UEE liaison officer, quietly decorated after the Save Stanton attacks." },
      { system: "Pyro", where: "anywhere in Pyro (a missing person)", activity: "rescue", contract: "A **Search** contract, or answer an **ECN** alert", find: "the Search target (finding them is the stand-in)", match: /search|missing|ecn|rescue/i,
        text: "{lieutenant} is ready to turn on {shadow}, for a guarantee of safety." },
      { system: "Pyro", where: "Ruin Station (orbiting Terminus)", activity: "combat", contract: "A **Mercenary** or **Bounty Hunter** ship-combat contract near Terminus", find: "the attack plan (any ship you down there is the stand-in)", match: /bounty|mercenary|terminus|ruin/i,
        text: "{shadow}'s next move is a staged massacre at Ruin Station, timed for when the UEE is watching." },
    ],
    tidbits: [
      { text: "{short}'s ship transponder was cloned. It pinged at a Slicer attack site on a day {they} were nowhere near it.", find: "a Frontier Fighter cache datapad (Pyro)" },
      { text: "{npc} once took money from a man in a Navy jacket to point out 'useful people'. {short} was on the list.", find: "the Derelict Outpost on Fuego" },
      { text: "A CFP file on {short} calls {them} 'sympathetic, deployable'. Nobody asked {short}.", find: "the CFP servers (Clear Citizens for Prosperity Servers)" },
      { text: "Someone from {home} is listed as a Frontier Fighter martyr. {short} went to their funeral, and they weren't in the box.", find: "the Ghost Arena at Ruin Station" },
      { text: "{short}'s face is in a Navy liaison's photo album, labelled 'fall guy, candidate'.", find: "the Executive Hangar registry (PYAM-EXHANG-0-1)" },
      { text: "The first big job {short} ever took was arranged by {shadow}. The pay came from UEE scrip.", find: "a hauling manifest between Stanton and Pyro" },
    ],
    bondHint: { text: "{short}'s name is on a list with your whole crew's. Above it, one word: Ruin.", find: "ship combat near Ruin Station (Terminus)" },
    finale: "Stop the massacre at Ruin Station, clear your names, and expose {truename}, or let the Empire believe the lie.",
    finalePlay: { system: "Pyro", where: "Ruin Station (orbiting Terminus)", contract: "Fight through Ruin Station's contested zone as a crew (the hostiles are {truename}'s strike team), then take a **Mercenary** or **Bounty Hunter** ship-combat contract near Terminus to bring down their escape ship", activity: "fps" },
    sideJobs: {
      Mercenary: "Every fight in Pyro is either the real war or {shadow}'s fake one. Find out which.",
      "Bounty Hunter": "Some bounty targets were posted by {shadow}, to silence people who knew too much.",
      Hauling: "Someone is moving guns under legal manifests. Yours could be one of them.",
      Delivery: "Packages between Stanton and Pyro are how the cells talk.",
      Investigation: "The truth about the Slicers is still out there, in files someone forgot to wipe.",
      Search: "The missing are often the ones who said no to {lieutenant}.",
      salvage: "Wrecks from the Slicer attacks still carry their transponders.",
      other: "{shadow} watches who works in Pyro. Make sure they see what you want them to see.",
    },
  },
  {
    id: "virgil",
    title: "The Quiet at Virgil",
    thread: "vanduul_nyx",
    systems: ["Nyx", "Pyro", "Stanton"],
    premise: "The Vanduul at the Virgil jump should have raided Nyx by now. They haven't. Instead, Levski's patrol routes keep leaking, the Shattered Blade has new money, and the only name anyone whispers is {shadow}.",
    truth: "{shadow} is {truename}, a human with a seat in Levski who made a deal with a Vanduul clan: Levski's routes and people in exchange for the clan's protection of a smuggling empire.",
    bond: "Here's what ties you together: you're on the manifest. {crew}, each of you was sold, one name at a time, as payment to the clan. The people who sold you are people from your own stories, and {truename} signed off on every one.",
    acts: [
      { name: "Silence", goal: "Find out why the Vanduul are waiting." },
      { name: "Leaks", goal: "Trace who is selling Levski's patrol routes." },
      { name: "The Broker", goal: "Find {shadow}'s go-between." },
      { name: "The Payment", goal: "Learn what the clan is being paid with." },
      { name: "Before the Raid", goal: "Stop the deal before the clan comes through the jump." },
    ],
    leads: [
      { system: "Nyx", where: "the space around Levski and the Glaciem Ring", activity: "combat", contract: "A **Mercenary** or **Bounty Hunter** ship-combat contract in Nyx", find: "your targets (the last one carries the black box)", match: /bounty|mercenary|vanduul|patrol/i,
        text: "A wrecked People's Alliance patrol was hit by Vanduul weapons in a sector only its own crew knew about." },
      { system: "Nyx", where: "the Keeger Belt", activity: "mining", contract: "Mining work for Recco Battaglia, or mine the Keeger Belt yourselves", find: "a full hold of Keeger Belt ore (the smuggler pays you in alloy)", match: /recco|mining|prospect|keeger/i,
        text: "A Keeger Belt smuggler gets paid in Vanduul-made alloy and won't say who from." },
      { system: "Nyx", where: "inside Levski", activity: "investigate", contract: "A **Levski Municipal Works** repair job inside Levski", find: "a maintenance terminal's access log", match: /levski|municipal|repair|maintenance/i,
        text: "Levski's patrol schedules were copied from inside the Assembly's own network, through a maintenance terminal." },
      { system: "Nyx", where: "the Alliance Aid convoy routes in Nyx", activity: "escort", contract: "**Alliance Aid** defence: protect the convoy from the Moraine gang", find: "the Moraine gang's orders", match: /alliance aid|moraine|defen|convoy/i,
        text: "{lieutenant} pays the Moraine gang to hit the aid convoys, so Levski stays desperate and grateful to whoever 'saves' it." },
      { system: "Nyx", where: "a QV Logistics station", activity: "fps", contract: "InterSec's **Vanduul-Tech Smugglers** (Junior Contractor rank)", find: "the data packets", match: /vanduul|smuggler|qv|intersec/i,
        text: "The smugglers carry human-made navigation keys for the Virgil jump." },
      { system: "Pyro", where: "Watcher's Depot, deep in XenoThreat territory on Terminus", activity: "fps", contract: "A **Mercenary** contract, or go in on foot", find: "the key-cutting rig", match: /mercenary|clear|terminus|xenothreat|watcher/i,
        text: "The navigation keys were cut on a rig in Pyro, guarded by XenoThreat. Even human supremacists will work for the Vanduul if the price is right." },
      { system: "Nyx", where: "a Shattered Blade QV Extraction station", activity: "rescue", contract: "InterSec's **Tactical Strike Group** op: rescue pilot Gabe Windell (a big op, 7+ ships)", find: "Gabe Windell, alive", match: /tactical|strike|windell|extraction/i,
        text: "Gabe Windell saw what the Shattered Blade loads onto the clan's ships. It isn't cargo. It's people, delivered alive." },
      { system: "Nyx", where: "a QV Breaker Station in the Keeger Belt", activity: "mining", contract: "**Operation Breaker Stations**: restore the station, fire the laser (12 Sadaryx for 3 lenses), go into the rock", find: "what's inside the asteroid", match: /breaker|sadaryx|rock breaker/i,
        text: "The last shipment of 'workers' was held inside a cracked asteroid at a Breaker Station, waiting for the clan." },
      { system: "Nyx", where: "Levski (the Molina Mold wards)", activity: "haul", contract: "**Alliance Aid** transport or collection: medical supplies and new air filters", find: "a sabotaged Gyson filter", match: /alliance aid|gyson|filter|molina|medical/i,
        text: "The Gyson filters didn't fail by accident. {shadow}'s people swapped them to empty whole sections of Levski, and nobody counts the missing in a plague." },
      { system: "Nyx", where: "Levski", activity: "rp", contract: "No contract needed: meet your contact in Levski", find: "Levski: land, walk to the Assembly area and play the meeting", match: /levski|assembly/i,
        text: "{shadow} has a seat in Levski's Assembly, under their real name, and the defence codes change hands at the next vote." },
    ],
    tidbits: [
      { text: "{npc} once sold a list of names to a broker in Levski. {short}'s was third.", find: "a Levski maintenance terminal" },
      { text: "A Shattered Blade manifest lists '{short}, healthy, delivery pending'.", find: "a QV Logistics station (Vanduul-Tech Smugglers)" },
      { text: "Someone from {home} vanished in the Molina Mold wards. Their bed was empty before the mold reached it.", find: "the Alliance Aid supply route" },
      { text: "{short}'s debts were bought up by a Nyx shell company. Nobody has ever asked {them} to pay.", find: "a Keeger Belt smuggler's payment records" },
      { text: "Gabe Windell remembers {short}'s name. The guards said it, and laughed.", find: "the Tactical Strike rescue" },
      { text: "A Vanduul-made navigation key has {short}'s ship registry burned into it.", find: "the key-cutting rig at Watcher's Depot" },
    ],
    bondHint: { text: "{short} is listed on the last Breaker Station manifest, together with everyone you fly with.", find: "inside the Breaker Station asteroid" },
    finale: "Expose {truename} in front of Levski's Assembly, and hold the line when the clan comes through the Virgil jump for its payment: you.",
    finalePlay: { system: "Nyx", where: "Levski and the space around it", contract: "Land in Levski and play the Assembly confrontation out loud, then take a **Mercenary** or **Bounty Hunter** ship-combat contract in Nyx (Vanduul, if they show, are the clan) and hold until it's done", activity: "combat" },
    sideJobs: {
      Mercenary: "Every gang in Nyx takes {shadow}'s money. Clear one and see who stops paying.",
      "Bounty Hunter": "Bounty targets in Nyx often know where the 'workers' are held.",
      Hauling: "Supplies to Levski keep people alive, and keep {shadow}'s plan from working.",
      Delivery: "Couriers in Nyx carry the broker's messages. Some of them, anyway.",
      Investigation: "Abandoned QV stations remember what passed through them.",
      Search: "In this story, the missing were sold. Find one, and you find the trail.",
      salvage: "Wrecks near the Virgil approach carry Vanduul scars, and human cargo holds.",
      other: "Every job in Nyx moves you closer to the Virgil jump, and to the people who sold you.",
    },
  },
  {
    id: "longknife",
    title: "Terra's Long Knife",
    thread: "terra",
    systems: ["Stanton", "Pyro"],
    premise: "Stanton's megacorps are bleeding money into Pyro, and Terra-backed businesses keep failing in strange ways. Someone is preparing the ground for a fight between Earth and Terra, and they sign their work {shadow}.",
    truth: "{shadow} is {truename}, an Earth-loyalist fixer arranging a crisis in Stanton that will be blamed on Terra, to justify stripping Terra's Senate seats before the next election.",
    bond: "Here's what ties you together: you built the frame yourselves. {crew}, every one of you was hired, at some point, through the same shell company in Area18, for jobs that looked ordinary. Every one of those jobs was a piece of {shadow}'s crisis.",
    acts: [
      { name: "Bad Luck", goal: "Work out why Terra-backed outfits keep failing." },
      { name: "The Paper Trail", goal: "Follow the money between Stanton and Pyro." },
      { name: "Hired Hands", goal: "Find who {shadow} pays to do the dirty work." },
      { name: "The Frame", goal: "Discover the crisis being prepared and who will take the blame." },
      { name: "The Senate Floor", goal: "Get the proof out before the frame closes." },
    ],
    leads: [
      { system: "Stanton", where: "a Stanton cargo route", activity: "haul", contract: "A **Hauling** contract in Stanton (Covalex, Ling Family Hauling or Red Wind Linehaul)", find: "the route data", match: /haul|cargo|covalex|ling|red wind/i,
        text: "Three Terra-backed haulers lost cargo to 'pirates' who knew their exact routes." },
      { system: "Stanton", where: "a pirate hideout in Stanton", activity: "bounty", contract: "A **Bounty Hunter** contract on a pirate in Stanton", find: "the pirate's paid-for route list", match: /bounty|pirate/i,
        text: "The routes were sold by a broker in Area18, paid from an account called {shadow}." },
      { system: "Stanton", where: "a Jumptown drug lab (Yela or Daymar)", activity: "fps", contract: "A **Mercenary** contract at a drug lab, or go in on foot", find: "the lab's books", match: /lab|jumptown|mercenary|clear/i,
        text: "Megacorp money is flowing to a Stanton gang through a shell company in Area18." },
      { system: "Stanton", where: "GrimHEX (Nine Tails territory)", activity: "bounty", contract: "A **Bounty Hunter** contract on a Nine Tails target", find: "the target's contact list", match: /bounty|nine tails|grim/i,
        text: "{lieutenant} handles the gang's side of the deal, from a back room at GrimHEX." },
      { system: "Stanton", where: "a Hathor orbital laser platform (Daymar or Aberdeen)", activity: "mining", contract: "No contract needed: **Align & Mine**. Align the PAFs, haul the batteries up, fire the laser", find: "the cave under the laser strike", match: /hathor|align|paf|olp|laser/i,
        text: "Hathor's abandoned platforms are being used as dead drops. Terra-made weapons are stored in the caves, waiting to be found 'by accident'." },
      { system: "Stanton", where: "Area18 (ArcCorp)", activity: "delivery", contract: "A **Delivery** contract to or from Area18", find: "the package's sender", match: /deliver|package|courier|area ?18/i,
        text: "A Terra Gazette journalist was paid to keep a story ready, to publish the day the crisis happens." },
      { system: "Stanton", where: "a microTech route (New Babbage)", activity: "haul", contract: "A **Hauling** contract carrying medical supplies", find: "the shipment's schedule", match: /medical|haul|microtech|new babbage/i,
        text: "The target is a microTech medical shipment. Its loss would hit regen supplies across Stanton." },
      { system: "Stanton", where: "Orison (the Siege of Orison)", activity: "fps", contract: "The instanced **Siege of Orison**", find: "Mendo Ren, dead (his recorder is the stand-in)", match: /orison|siege|nine tails|ren/i,
        text: "{lieutenant} keeps a recorded call with {shadow} as insurance. Mendo Ren had a copy." },
      { system: "Stanton", where: "an Onyx Facility", activity: "investigate", contract: "An **Investigation** contract at an Onyx Facility", find: "the shell company's records in ASD's files", match: /investigat|onyx|dossier/i,
        text: "The Area18 shell company's real owner is a senior Earth-loyalist political fixer, and ASD's lawyers set it up." },
      { system: "Stanton", where: "the microTech shipment's route", activity: "escort", contract: "Fly escort on a crewmate's **Hauling** run, or a **Mercenary** defend job", find: "the attackers on the run (shooting them down is the stand-in)", match: /defend|escort|mercenary/i,
        text: "{shadow} will be in Stanton in person, to watch the crisis unfold. For once, they can be reached." },
    ],
    tidbits: [
      { text: "{short}'s first steady job was paid through a shell company in Area18. It still has {their} file.", find: "a Delivery contract to Area18" },
      { text: "{npc} once delivered a package for {short}, and never said what was in it. It was a weapon with a Terra serial number.", find: "a Hathor laser cave" },
      { text: "A Jumptown lab's books list {short} as 'contractor, reliable, doesn't ask'.", find: "a Jumptown drug lab" },
      { text: "Someone from {home} works for the Terra Gazette, and has a story about {short} ready to publish.", find: "Area18: land and walk the plaza, or take any Delivery contract there" },
      { text: "{short}'s ship was hired once for a 'survey' over Daymar. It was mapping a dead drop.", find: "a Hathor orbital laser platform" },
      { text: "{short}'s name is in Mendo Ren's recorder, as someone {shadow} 'already owns'.", find: "the Siege of Orison" },
    ],
    bondHint: { text: "The shell company's payroll has {short}'s name on it, and every crewmate's, each paid for one piece of the plan.", find: "an Investigation contract at an Onyx Facility (the shell company's files)" },
    finale: "Stop the strike on the medical shipment and get {lieutenant}'s recording to someone who'll use it, before {truename} disappears.",
    finalePlay: { system: "Stanton", where: "a run to New Babbage (microTech)", contract: "One crewmate takes a **Hauling** contract carrying medical supplies to New Babbage, the rest fly escort; a **Mercenary** defend or **Bounty Hunter** contract on the way stands in for the strike team. A **Delivery** to Area18 afterwards is the recording reaching the press", activity: "escort" },
    sideJobs: {
      Mercenary: "Every gang you hit in Stanton is someone {shadow} paid. Check their pockets.",
      "Bounty Hunter": "Bounty targets in Stanton have been very well paid lately. Find out by whom.",
      Hauling: "Was this job really yours, or did the shell company arrange it? Check who posted it.",
      Delivery: "Packages are how the frame is built. Know what you're carrying.",
      Investigation: "The paper trail runs through ASD's lawyers. Any file could have it.",
      Search: "People who saw the plan tend to go missing.",
      salvage: "Wrecks of Terra-backed haulers still carry their logs.",
      other: "Every job you take could be a piece of {shadow}'s plan. This time, know which piece.",
    },
  },
];

export const SAGA_ACT_LEADS = 2;
export const SAGA_THREAT_START = 3;
export const SAGA_THREAT_MAX = 10;
// Side jobs (any completed contract that isn't the current lead) dig up a personal tidbit every this many.
export const SIDE_JOBS_PER_TIDBIT = 2;
